// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type AddressUnionTypeEnum int
const (

	 AddressUnionTypeEnumNull AddressUnionTypeEnum = 0

	 AddressUnionTypeEnumString AddressUnionTypeEnum = 1

)

type AddressUnion struct {

	Null *types.NullVal

	String string

	UnionType AddressUnionTypeEnum
}

func writeAddressUnion(r *AddressUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case AddressUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case AddressUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *AddressUnion")
}

func NewAddressUnion() *AddressUnion {
	return &AddressUnion{}
}

func (_ *AddressUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *AddressUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *AddressUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *AddressUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *AddressUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *AddressUnion) SetString(v string) { panic("Unsupported operation") }
func (r *AddressUnion) SetLong(v int64) { 
	r.UnionType = (AddressUnionTypeEnum)(v)
}
func (r *AddressUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *AddressUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *AddressUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *AddressUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *AddressUnion) Finalize()  { }
