// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type BrandUnionTypeEnum int
const (

	 BrandUnionTypeEnumNull BrandUnionTypeEnum = 0

	 BrandUnionTypeEnumString BrandUnionTypeEnum = 1

)

type BrandUnion struct {

	Null *types.NullVal

	String string

	UnionType BrandUnionTypeEnum
}

func writeBrandUnion(r *BrandUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case BrandUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case BrandUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *BrandUnion")
}

func NewBrandUnion() *BrandUnion {
	return &BrandUnion{}
}

func (_ *BrandUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *BrandUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *BrandUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *BrandUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *BrandUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *BrandUnion) SetString(v string) { panic("Unsupported operation") }
func (r *BrandUnion) SetLong(v int64) { 
	r.UnionType = (BrandUnionTypeEnum)(v)
}
func (r *BrandUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *BrandUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *BrandUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *BrandUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *BrandUnion) Finalize()  { }
