// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type ConfigUnionTypeEnum int
const (

	 ConfigUnionTypeEnumNull ConfigUnionTypeEnum = 0

	 ConfigUnionTypeEnumString ConfigUnionTypeEnum = 1

)

type ConfigUnion struct {

	Null *types.NullVal

	String string

	UnionType ConfigUnionTypeEnum
}

func writeConfigUnion(r *ConfigUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case ConfigUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case ConfigUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *ConfigUnion")
}

func NewConfigUnion() *ConfigUnion {
	return &ConfigUnion{}
}

func (_ *ConfigUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *ConfigUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *ConfigUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *ConfigUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *ConfigUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *ConfigUnion) SetString(v string) { panic("Unsupported operation") }
func (r *ConfigUnion) SetLong(v int64) { 
	r.UnionType = (ConfigUnionTypeEnum)(v)
}
func (r *ConfigUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *ConfigUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *ConfigUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ConfigUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *ConfigUnion) Finalize()  { }
