// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type CurrentGameConfigUnionTypeEnum int
const (

	 CurrentGameConfigUnionTypeEnumNull CurrentGameConfigUnionTypeEnum = 0

	 CurrentGameConfigUnionTypeEnumString CurrentGameConfigUnionTypeEnum = 1

)

type CurrentGameConfigUnion struct {

	Null *types.NullVal

	String string

	UnionType CurrentGameConfigUnionTypeEnum
}

func writeCurrentGameConfigUnion(r *CurrentGameConfigUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case CurrentGameConfigUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case CurrentGameConfigUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *CurrentGameConfigUnion")
}

func NewCurrentGameConfigUnion() *CurrentGameConfigUnion {
	return &CurrentGameConfigUnion{}
}

func (_ *CurrentGameConfigUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *CurrentGameConfigUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *CurrentGameConfigUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *CurrentGameConfigUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *CurrentGameConfigUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *CurrentGameConfigUnion) SetString(v string) { panic("Unsupported operation") }
func (r *CurrentGameConfigUnion) SetLong(v int64) { 
	r.UnionType = (CurrentGameConfigUnionTypeEnum)(v)
}
func (r *CurrentGameConfigUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *CurrentGameConfigUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *CurrentGameConfigUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *CurrentGameConfigUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *CurrentGameConfigUnion) Finalize()  { }
