// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type CurrentGameIDUnionTypeEnum int
const (

	 CurrentGameIDUnionTypeEnumNull CurrentGameIDUnionTypeEnum = 0

	 CurrentGameIDUnionTypeEnumString CurrentGameIDUnionTypeEnum = 1

)

type CurrentGameIDUnion struct {

	Null *types.NullVal

	String string

	UnionType CurrentGameIDUnionTypeEnum
}

func writeCurrentGameIDUnion(r *CurrentGameIDUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case CurrentGameIDUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case CurrentGameIDUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *CurrentGameIDUnion")
}

func NewCurrentGameIDUnion() *CurrentGameIDUnion {
	return &CurrentGameIDUnion{}
}

func (_ *CurrentGameIDUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *CurrentGameIDUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *CurrentGameIDUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *CurrentGameIDUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *CurrentGameIDUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *CurrentGameIDUnion) SetString(v string) { panic("Unsupported operation") }
func (r *CurrentGameIDUnion) SetLong(v int64) { 
	r.UnionType = (CurrentGameIDUnionTypeEnum)(v)
}
func (r *CurrentGameIDUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *CurrentGameIDUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *CurrentGameIDUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *CurrentGameIDUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *CurrentGameIDUnion) Finalize()  { }
