// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Customer_signinUnionTypeEnum int
const (

	 Customer_signinUnionTypeEnumNull Customer_signinUnionTypeEnum = 0

	 Customer_signinUnionTypeEnumRequestCustomerSignin Customer_signinUnionTypeEnum = 1

)

type Customer_signinUnion struct {

	Null *types.NullVal

	RequestCustomerSignin *RequestCustomerSignin

	UnionType Customer_signinUnionTypeEnum
}

func writeCustomer_signinUnion(r *Customer_signinUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Customer_signinUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Customer_signinUnionTypeEnumRequestCustomerSignin:
		return writeRequestCustomerSignin(r.RequestCustomerSignin, w)
        
	}
	return fmt.Errorf("invalid value for *Customer_signinUnion")
}

func NewCustomer_signinUnion() *Customer_signinUnion {
	return &Customer_signinUnion{}
}

func (_ *Customer_signinUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Customer_signinUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Customer_signinUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Customer_signinUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Customer_signinUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Customer_signinUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Customer_signinUnion) SetLong(v int64) { 
	r.UnionType = (Customer_signinUnionTypeEnum)(v)
}
func (r *Customer_signinUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestCustomerSignin = NewRequestCustomerSignin()
		
		
		return r.RequestCustomerSignin
		
	
	}
	panic("Unknown field index")
}
func (_ *Customer_signinUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Customer_signinUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Customer_signinUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Customer_signinUnion) Finalize()  { }
