// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/vm"
)

  
type CustomerState int32

const (

	CustomerStateIdle CustomerState = 0

	CustomerStateDuring_chat CustomerState = 1

	CustomerStateGame CustomerState = 2

	CustomerStateBrowse_product CustomerState = 3

	CustomerStatePaying CustomerState = 4

)

func (e CustomerState) String() string {
	switch e {

	case CustomerStateIdle:
		return "idle"

	case CustomerStateDuring_chat:
		return "during_chat"

	case CustomerStateGame:
		return "game"

	case CustomerStateBrowse_product:
		return "browse_product"

	case CustomerStatePaying:
		return "paying"

	}
	return "unknown"
}

func writeCustomerState(r CustomerState, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewCustomerStateValue(raw string) (r CustomerState, err error) {
	switch raw {

	case "idle":
		return CustomerStateIdle, nil

	case "during_chat":
		return CustomerStateDuring_chat, nil

	case "game":
		return CustomerStateGame, nil

	case "browse_product":
		return CustomerStateBrowse_product, nil

	case "paying":
		return CustomerStatePaying, nil

	}

	return -1, fmt.Errorf("invalid value for CustomerState: '%s'", raw)
}
