// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Customer_mobile_regionUnionTypeEnum int
const (

	 Customer_mobile_regionUnionTypeEnumNull Customer_mobile_regionUnionTypeEnum = 0

	 Customer_mobile_regionUnionTypeEnumString Customer_mobile_regionUnionTypeEnum = 1

)

type Customer_mobile_regionUnion struct {

	Null *types.NullVal

	String string

	UnionType Customer_mobile_regionUnionTypeEnum
}

func writeCustomer_mobile_regionUnion(r *Customer_mobile_regionUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Customer_mobile_regionUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Customer_mobile_regionUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *Customer_mobile_regionUnion")
}

func NewCustomer_mobile_regionUnion() *Customer_mobile_regionUnion {
	return &Customer_mobile_regionUnion{}
}

func (_ *Customer_mobile_regionUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Customer_mobile_regionUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Customer_mobile_regionUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Customer_mobile_regionUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Customer_mobile_regionUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Customer_mobile_regionUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Customer_mobile_regionUnion) SetLong(v int64) { 
	r.UnionType = (Customer_mobile_regionUnionTypeEnum)(v)
}
func (r *Customer_mobile_regionUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *Customer_mobile_regionUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Customer_mobile_regionUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Customer_mobile_regionUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Customer_mobile_regionUnion) Finalize()  { }
