// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Customer_usernameUnionTypeEnum int
const (

	 Customer_usernameUnionTypeEnumNull Customer_usernameUnionTypeEnum = 0

	 Customer_usernameUnionTypeEnumString Customer_usernameUnionTypeEnum = 1

)

type Customer_usernameUnion struct {

	Null *types.NullVal

	String string

	UnionType Customer_usernameUnionTypeEnum
}

func writeCustomer_usernameUnion(r *Customer_usernameUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Customer_usernameUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Customer_usernameUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *Customer_usernameUnion")
}

func NewCustomer_usernameUnion() *Customer_usernameUnion {
	return &Customer_usernameUnion{}
}

func (_ *Customer_usernameUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Customer_usernameUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Customer_usernameUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Customer_usernameUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Customer_usernameUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Customer_usernameUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Customer_usernameUnion) SetLong(v int64) { 
	r.UnionType = (Customer_usernameUnionTypeEnum)(v)
}
func (r *Customer_usernameUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *Customer_usernameUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Customer_usernameUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Customer_usernameUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Customer_usernameUnion) Finalize()  { }
