// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Customer_update_stateUnionTypeEnum int
const (

	 Customer_update_stateUnionTypeEnumNull Customer_update_stateUnionTypeEnum = 0

	 Customer_update_stateUnionTypeEnumRequestCustomerUpdateState Customer_update_stateUnionTypeEnum = 1

)

type Customer_update_stateUnion struct {

	Null *types.NullVal

	RequestCustomerUpdateState *RequestCustomerUpdateState

	UnionType Customer_update_stateUnionTypeEnum
}

func writeCustomer_update_stateUnion(r *Customer_update_stateUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Customer_update_stateUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Customer_update_stateUnionTypeEnumRequestCustomerUpdateState:
		return writeRequestCustomerUpdateState(r.RequestCustomerUpdateState, w)
        
	}
	return fmt.Errorf("invalid value for *Customer_update_stateUnion")
}

func NewCustomer_update_stateUnion() *Customer_update_stateUnion {
	return &Customer_update_stateUnion{}
}

func (_ *Customer_update_stateUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Customer_update_stateUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Customer_update_stateUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Customer_update_stateUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Customer_update_stateUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Customer_update_stateUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Customer_update_stateUnion) SetLong(v int64) { 
	r.UnionType = (Customer_update_stateUnionTypeEnum)(v)
}
func (r *Customer_update_stateUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestCustomerUpdateState = NewRequestCustomerUpdateState()
		
		
		return r.RequestCustomerUpdateState
		
	
	}
	panic("Unknown field index")
}
func (_ *Customer_update_stateUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Customer_update_stateUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Customer_update_stateUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Customer_update_stateUnion) Finalize()  { }
