// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Customer_idcardUnionTypeEnum int
const (

	 Customer_idcardUnionTypeEnumNull Customer_idcardUnionTypeEnum = 0

	 Customer_idcardUnionTypeEnumString Customer_idcardUnionTypeEnum = 1

)

type Customer_idcardUnion struct {

	Null *types.NullVal

	String string

	UnionType Customer_idcardUnionTypeEnum
}

func writeCustomer_idcardUnion(r *Customer_idcardUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Customer_idcardUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Customer_idcardUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *Customer_idcardUnion")
}

func NewCustomer_idcardUnion() *Customer_idcardUnion {
	return &Customer_idcardUnion{}
}

func (_ *Customer_idcardUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Customer_idcardUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Customer_idcardUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Customer_idcardUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Customer_idcardUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Customer_idcardUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Customer_idcardUnion) SetLong(v int64) { 
	r.UnionType = (Customer_idcardUnionTypeEnum)(v)
}
func (r *Customer_idcardUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *Customer_idcardUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Customer_idcardUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Customer_idcardUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Customer_idcardUnion) Finalize()  { }
