// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Customer_start_gameUnionTypeEnum int
const (

	 Customer_start_gameUnionTypeEnumNull Customer_start_gameUnionTypeEnum = 0

	 Customer_start_gameUnionTypeEnumRequestCustomerStartGame Customer_start_gameUnionTypeEnum = 1

)

type Customer_start_gameUnion struct {

	Null *types.NullVal

	RequestCustomerStartGame *RequestCustomerStartGame

	UnionType Customer_start_gameUnionTypeEnum
}

func writeCustomer_start_gameUnion(r *Customer_start_gameUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Customer_start_gameUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Customer_start_gameUnionTypeEnumRequestCustomerStartGame:
		return writeRequestCustomerStartGame(r.RequestCustomerStartGame, w)
        
	}
	return fmt.Errorf("invalid value for *Customer_start_gameUnion")
}

func NewCustomer_start_gameUnion() *Customer_start_gameUnion {
	return &Customer_start_gameUnion{}
}

func (_ *Customer_start_gameUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Customer_start_gameUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Customer_start_gameUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Customer_start_gameUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Customer_start_gameUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Customer_start_gameUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Customer_start_gameUnion) SetLong(v int64) { 
	r.UnionType = (Customer_start_gameUnionTypeEnum)(v)
}
func (r *Customer_start_gameUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestCustomerStartGame = NewRequestCustomerStartGame()
		
		
		return r.RequestCustomerStartGame
		
	
	}
	panic("Unknown field index")
}
func (_ *Customer_start_gameUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Customer_start_gameUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Customer_start_gameUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Customer_start_gameUnion) Finalize()  { }
