// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Customer_auction_bidUnionTypeEnum int
const (

	 Customer_auction_bidUnionTypeEnumNull Customer_auction_bidUnionTypeEnum = 0

	 Customer_auction_bidUnionTypeEnumRequestCustomerAuctionBid Customer_auction_bidUnionTypeEnum = 1

)

type Customer_auction_bidUnion struct {

	Null *types.NullVal

	RequestCustomerAuctionBid *RequestCustomerAuctionBid

	UnionType Customer_auction_bidUnionTypeEnum
}

func writeCustomer_auction_bidUnion(r *Customer_auction_bidUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Customer_auction_bidUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Customer_auction_bidUnionTypeEnumRequestCustomerAuctionBid:
		return writeRequestCustomerAuctionBid(r.RequestCustomerAuctionBid, w)
        
	}
	return fmt.Errorf("invalid value for *Customer_auction_bidUnion")
}

func NewCustomer_auction_bidUnion() *Customer_auction_bidUnion {
	return &Customer_auction_bidUnion{}
}

func (_ *Customer_auction_bidUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Customer_auction_bidUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Customer_auction_bidUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Customer_auction_bidUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Customer_auction_bidUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Customer_auction_bidUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Customer_auction_bidUnion) SetLong(v int64) { 
	r.UnionType = (Customer_auction_bidUnionTypeEnum)(v)
}
func (r *Customer_auction_bidUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestCustomerAuctionBid = NewRequestCustomerAuctionBid()
		
		
		return r.RequestCustomerAuctionBid
		
	
	}
	panic("Unknown field index")
}
func (_ *Customer_auction_bidUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Customer_auction_bidUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Customer_auction_bidUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Customer_auction_bidUnion) Finalize()  { }
