// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Customer_mobileUnionTypeEnum int
const (

	 Customer_mobileUnionTypeEnumNull Customer_mobileUnionTypeEnum = 0

	 Customer_mobileUnionTypeEnumString Customer_mobileUnionTypeEnum = 1

)

type Customer_mobileUnion struct {

	Null *types.NullVal

	String string

	UnionType Customer_mobileUnionTypeEnum
}

func writeCustomer_mobileUnion(r *Customer_mobileUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Customer_mobileUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Customer_mobileUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *Customer_mobileUnion")
}

func NewCustomer_mobileUnion() *Customer_mobileUnion {
	return &Customer_mobileUnion{}
}

func (_ *Customer_mobileUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Customer_mobileUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Customer_mobileUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Customer_mobileUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Customer_mobileUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Customer_mobileUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Customer_mobileUnion) SetLong(v int64) { 
	r.UnionType = (Customer_mobileUnionTypeEnum)(v)
}
func (r *Customer_mobileUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *Customer_mobileUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Customer_mobileUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Customer_mobileUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Customer_mobileUnion) Finalize()  { }
