// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Error_messageUnionTypeEnum int
const (

	 Error_messageUnionTypeEnumNull Error_messageUnionTypeEnum = 0

	 Error_messageUnionTypeEnumString Error_messageUnionTypeEnum = 1

)

type Error_messageUnion struct {

	Null *types.NullVal

	String string

	UnionType Error_messageUnionTypeEnum
}

func writeError_messageUnion(r *Error_messageUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Error_messageUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Error_messageUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *Error_messageUnion")
}

func NewError_messageUnion() *Error_messageUnion {
	return &Error_messageUnion{}
}

func (_ *Error_messageUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Error_messageUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Error_messageUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Error_messageUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Error_messageUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Error_messageUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Error_messageUnion) SetLong(v int64) { 
	r.UnionType = (Error_messageUnionTypeEnum)(v)
}
func (r *Error_messageUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *Error_messageUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Error_messageUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Error_messageUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Error_messageUnion) Finalize()  { }
