// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/vm"
)

  
type GlobalState int32

const (

	GlobalStateAwating_starting GlobalState = 0

	GlobalStateStarting_animations GlobalState = 1

	GlobalStateSpeeching GlobalState = 2

	GlobalStateAution GlobalState = 3

	GlobalStateProducts GlobalState = 4

	GlobalStateEarnest_money GlobalState = 5

	GlobalStateDiscount_strategy GlobalState = 6

	GlobalStateChat_with_advisor GlobalState = 7

	GlobalStateActivity_ends GlobalState = 8

)

func (e GlobalState) String() string {
	switch e {

	case GlobalStateAwating_starting:
		return "awating_starting"

	case GlobalStateStarting_animations:
		return "starting_animations"

	case GlobalStateSpeeching:
		return "speeching"

	case GlobalStateAution:
		return "aution"

	case GlobalStateProducts:
		return "products"

	case GlobalStateEarnest_money:
		return "earnest_money"

	case GlobalStateDiscount_strategy:
		return "discount_strategy"

	case GlobalStateChat_with_advisor:
		return "chat_with_advisor"

	case GlobalStateActivity_ends:
		return "activity_ends"

	}
	return "unknown"
}

func writeGlobalState(r GlobalState, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewGlobalStateValue(raw string) (r GlobalState, err error) {
	switch raw {

	case "awating_starting":
		return GlobalStateAwating_starting, nil

	case "starting_animations":
		return GlobalStateStarting_animations, nil

	case "speeching":
		return GlobalStateSpeeching, nil

	case "aution":
		return GlobalStateAution, nil

	case "products":
		return GlobalStateProducts, nil

	case "earnest_money":
		return GlobalStateEarnest_money, nil

	case "discount_strategy":
		return GlobalStateDiscount_strategy, nil

	case "chat_with_advisor":
		return GlobalStateChat_with_advisor, nil

	case "activity_ends":
		return GlobalStateActivity_ends, nil

	}

	return -1, fmt.Errorf("invalid value for GlobalState: '%s'", raw)
}
