// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Goods_nameUnionTypeEnum int
const (

	 Goods_nameUnionTypeEnumNull Goods_nameUnionTypeEnum = 0

	 Goods_nameUnionTypeEnumString Goods_nameUnionTypeEnum = 1

)

type Goods_nameUnion struct {

	Null *types.NullVal

	String string

	UnionType Goods_nameUnionTypeEnum
}

func writeGoods_nameUnion(r *Goods_nameUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Goods_nameUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Goods_nameUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *Goods_nameUnion")
}

func NewGoods_nameUnion() *Goods_nameUnion {
	return &Goods_nameUnion{}
}

func (_ *Goods_nameUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Goods_nameUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Goods_nameUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Goods_nameUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Goods_nameUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Goods_nameUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Goods_nameUnion) SetLong(v int64) { 
	r.UnionType = (Goods_nameUnionTypeEnum)(v)
}
func (r *Goods_nameUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *Goods_nameUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Goods_nameUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Goods_nameUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Goods_nameUnion) Finalize()  { }
