// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Host_switch_stateUnionTypeEnum int
const (

	 Host_switch_stateUnionTypeEnumNull Host_switch_stateUnionTypeEnum = 0

	 Host_switch_stateUnionTypeEnumRequestHostSwitchState Host_switch_stateUnionTypeEnum = 1

)

type Host_switch_stateUnion struct {

	Null *types.NullVal

	RequestHostSwitchState *RequestHostSwitchState

	UnionType Host_switch_stateUnionTypeEnum
}

func writeHost_switch_stateUnion(r *Host_switch_stateUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Host_switch_stateUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Host_switch_stateUnionTypeEnumRequestHostSwitchState:
		return writeRequestHostSwitchState(r.RequestHostSwitchState, w)
        
	}
	return fmt.Errorf("invalid value for *Host_switch_stateUnion")
}

func NewHost_switch_stateUnion() *Host_switch_stateUnion {
	return &Host_switch_stateUnion{}
}

func (_ *Host_switch_stateUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Host_switch_stateUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Host_switch_stateUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Host_switch_stateUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Host_switch_stateUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Host_switch_stateUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Host_switch_stateUnion) SetLong(v int64) { 
	r.UnionType = (Host_switch_stateUnionTypeEnum)(v)
}
func (r *Host_switch_stateUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestHostSwitchState = NewRequestHostSwitchState()
		
		
		return r.RequestHostSwitchState
		
	
	}
	panic("Unknown field index")
}
func (_ *Host_switch_stateUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Host_switch_stateUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Host_switch_stateUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Host_switch_stateUnion) Finalize()  { }
