// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type IdcardUnionTypeEnum int
const (

	 IdcardUnionTypeEnumNull IdcardUnionTypeEnum = 0

	 IdcardUnionTypeEnumString IdcardUnionTypeEnum = 1

)

type IdcardUnion struct {

	Null *types.NullVal

	String string

	UnionType IdcardUnionTypeEnum
}

func writeIdcardUnion(r *IdcardUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case IdcardUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case IdcardUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *IdcardUnion")
}

func NewIdcardUnion() *IdcardUnion {
	return &IdcardUnion{}
}

func (_ *IdcardUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *IdcardUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *IdcardUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *IdcardUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *IdcardUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *IdcardUnion) SetString(v string) { panic("Unsupported operation") }
func (r *IdcardUnion) SetLong(v int64) { 
	r.UnionType = (IdcardUnionTypeEnum)(v)
}
func (r *IdcardUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *IdcardUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *IdcardUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *IdcardUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *IdcardUnion) Finalize()  { }
