// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type InteriorUnionTypeEnum int
const (

	 InteriorUnionTypeEnumNull InteriorUnionTypeEnum = 0

	 InteriorUnionTypeEnumString InteriorUnionTypeEnum = 1

)

type InteriorUnion struct {

	Null *types.NullVal

	String string

	UnionType InteriorUnionTypeEnum
}

func writeInteriorUnion(r *InteriorUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case InteriorUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case InteriorUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *InteriorUnion")
}

func NewInteriorUnion() *InteriorUnion {
	return &InteriorUnion{}
}

func (_ *InteriorUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *InteriorUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *InteriorUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *InteriorUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *InteriorUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *InteriorUnion) SetString(v string) { panic("Unsupported operation") }
func (r *InteriorUnion) SetLong(v int64) { 
	r.UnionType = (InteriorUnionTypeEnum)(v)
}
func (r *InteriorUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *InteriorUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *InteriorUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *InteriorUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *InteriorUnion) Finalize()  { }
