// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type KeyUnionTypeEnum int
const (

	 KeyUnionTypeEnumNull KeyUnionTypeEnum = 0

	 KeyUnionTypeEnumString KeyUnionTypeEnum = 1

)

type KeyUnion struct {

	Null *types.NullVal

	String string

	UnionType KeyUnionTypeEnum
}

func writeKeyUnion(r *KeyUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case KeyUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case KeyUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *KeyUnion")
}

func NewKeyUnion() *KeyUnion {
	return &KeyUnion{}
}

func (_ *KeyUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *KeyUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *KeyUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *KeyUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *KeyUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *KeyUnion) SetString(v string) { panic("Unsupported operation") }
func (r *KeyUnion) SetLong(v int64) { 
	r.UnionType = (KeyUnionTypeEnum)(v)
}
func (r *KeyUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *KeyUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *KeyUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *KeyUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *KeyUnion) Finalize()  { }
