// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Message_customer_infoUnionTypeEnum int
const (

	 Message_customer_infoUnionTypeEnumNull Message_customer_infoUnionTypeEnum = 0

	 Message_customer_infoUnionTypeEnumMessageCustomersInfo Message_customer_infoUnionTypeEnum = 1

)

type Message_customer_infoUnion struct {

	Null *types.NullVal

	MessageCustomersInfo *MessageCustomersInfo

	UnionType Message_customer_infoUnionTypeEnum
}

func writeMessage_customer_infoUnion(r *Message_customer_infoUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Message_customer_infoUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Message_customer_infoUnionTypeEnumMessageCustomersInfo:
		return writeMessageCustomersInfo(r.MessageCustomersInfo, w)
        
	}
	return fmt.Errorf("invalid value for *Message_customer_infoUnion")
}

func NewMessage_customer_infoUnion() *Message_customer_infoUnion {
	return &Message_customer_infoUnion{}
}

func (_ *Message_customer_infoUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Message_customer_infoUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Message_customer_infoUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Message_customer_infoUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Message_customer_infoUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Message_customer_infoUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Message_customer_infoUnion) SetLong(v int64) { 
	r.UnionType = (Message_customer_infoUnionTypeEnum)(v)
}
func (r *Message_customer_infoUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.MessageCustomersInfo = NewMessageCustomersInfo()
		
		
		return r.MessageCustomersInfo
		
	
	}
	panic("Unknown field index")
}
func (_ *Message_customer_infoUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Message_customer_infoUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Message_customer_infoUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Message_customer_infoUnion) Finalize()  { }
