// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type MessageCustomersInfo struct {

	
	
		Mobile *MobileUnion
	

	
	
		MobileRegion *MobileRegionUnion
	

	
	
		Idcard *IdcardUnion
	

	
	
		Username *UsernameUnion
	

}

func NewMessageCustomersInfo() (*MessageCustomersInfo) {
	return &MessageCustomersInfo{}
}

func DeserializeMessageCustomersInfo(r io.Reader) (*MessageCustomersInfo, error) {
	t := NewMessageCustomersInfo()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeMessageCustomersInfoFromSchema(r io.Reader, schema string) (*MessageCustomersInfo, error) {
	t := NewMessageCustomersInfo()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeMessageCustomersInfo(r *MessageCustomersInfo, w io.Writer) error {
	var err error
	
	err = writeMobileUnion( r.Mobile, w)
	if err != nil {
		return err			
	}
	
	err = writeMobileRegionUnion( r.MobileRegion, w)
	if err != nil {
		return err			
	}
	
	err = writeIdcardUnion( r.Idcard, w)
	if err != nil {
		return err			
	}
	
	err = writeUsernameUnion( r.Username, w)
	if err != nil {
		return err			
	}
	
	return err
}

func (r *MessageCustomersInfo) Serialize(w io.Writer) error {
	return writeMessageCustomersInfo(r, w)
}

func (r *MessageCustomersInfo) Schema() string {
	return "{\"fields\":[{\"name\":\"mobile\",\"type\":[\"null\",\"string\"]},{\"name\":\"mobileRegion\",\"type\":[\"null\",\"string\"]},{\"name\":\"idcard\",\"type\":[\"null\",\"string\"]},{\"name\":\"username\",\"type\":[\"null\",\"string\"]}],\"name\":\"proto.MessageCustomersInfo\",\"type\":\"record\"}"
}

func (r *MessageCustomersInfo) SchemaName() string {
	return "proto.MessageCustomersInfo"
}

func (_ *MessageCustomersInfo) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *MessageCustomersInfo) SetInt(v int32) { panic("Unsupported operation") }
func (_ *MessageCustomersInfo) SetLong(v int64) { panic("Unsupported operation") }
func (_ *MessageCustomersInfo) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *MessageCustomersInfo) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *MessageCustomersInfo) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *MessageCustomersInfo) SetString(v string) { panic("Unsupported operation") }
func (_ *MessageCustomersInfo) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *MessageCustomersInfo) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
			r.Mobile = NewMobileUnion()
	
		
		
			return r.Mobile
		
	
	case 1:
		
			r.MobileRegion = NewMobileRegionUnion()
	
		
		
			return r.MobileRegion
		
	
	case 2:
		
			r.Idcard = NewIdcardUnion()
	
		
		
			return r.Idcard
		
	
	case 3:
		
			r.Username = NewUsernameUnion()
	
		
		
			return r.Username
		
	
	}
	panic("Unknown field index")
}

func (r *MessageCustomersInfo) SetDefault(i int) {
	switch (i) {
	
        
	
        
	
        
	
        
	
	}
	panic("Unknown field index")
}

func (_ *MessageCustomersInfo) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *MessageCustomersInfo) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *MessageCustomersInfo) Finalize() { }
