// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type MessageSession struct {

	
	
		Sid *SidUnion
	

}

func NewMessageSession() (*MessageSession) {
	return &MessageSession{}
}

func DeserializeMessageSession(r io.Reader) (*MessageSession, error) {
	t := NewMessageSession()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeMessageSessionFromSchema(r io.Reader, schema string) (*MessageSession, error) {
	t := NewMessageSession()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeMessageSession(r *MessageSession, w io.Writer) error {
	var err error
	
	err = writeSidUnion( r.Sid, w)
	if err != nil {
		return err			
	}
	
	return err
}

func (r *MessageSession) Serialize(w io.Writer) error {
	return writeMessageSession(r, w)
}

func (r *MessageSession) Schema() string {
	return "{\"fields\":[{\"name\":\"sid\",\"type\":[\"null\",\"string\"]}],\"name\":\"proto.MessageSession\",\"type\":\"record\"}"
}

func (r *MessageSession) SchemaName() string {
	return "proto.MessageSession"
}

func (_ *MessageSession) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *MessageSession) SetInt(v int32) { panic("Unsupported operation") }
func (_ *MessageSession) SetLong(v int64) { panic("Unsupported operation") }
func (_ *MessageSession) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *MessageSession) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *MessageSession) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *MessageSession) SetString(v string) { panic("Unsupported operation") }
func (_ *MessageSession) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *MessageSession) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
			r.Sid = NewSidUnion()
	
		
		
			return r.Sid
		
	
	}
	panic("Unknown field index")
}

func (r *MessageSession) SetDefault(i int) {
	switch (i) {
	
        
	
	}
	panic("Unknown field index")
}

func (_ *MessageSession) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *MessageSession) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *MessageSession) Finalize() { }
