// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type MessageAuctionInfo struct {

	
	
		Remain_seconds int32
	

	
	
		Goods *GoodsUnion
	

}

func NewMessageAuctionInfo() (*MessageAuctionInfo) {
	return &MessageAuctionInfo{}
}

func DeserializeMessageAuctionInfo(r io.Reader) (*MessageAuctionInfo, error) {
	t := NewMessageAuctionInfo()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeMessageAuctionInfoFromSchema(r io.Reader, schema string) (*MessageAuctionInfo, error) {
	t := NewMessageAuctionInfo()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeMessageAuctionInfo(r *MessageAuctionInfo, w io.Writer) error {
	var err error
	
	err = vm.WriteInt( r.Remain_seconds, w)
	if err != nil {
		return err			
	}
	
	err = writeGoodsUnion( r.Goods, w)
	if err != nil {
		return err			
	}
	
	return err
}

func (r *MessageAuctionInfo) Serialize(w io.Writer) error {
	return writeMessageAuctionInfo(r, w)
}

func (r *MessageAuctionInfo) Schema() string {
	return "{\"fields\":[{\"name\":\"remain_seconds\",\"type\":\"int\"},{\"name\":\"goods\",\"type\":[\"null\",{\"fields\":[{\"name\":\"goods_id\",\"type\":\"int\"},{\"name\":\"goods_name\",\"type\":[\"null\",\"string\"]},{\"name\":\"original_price\",\"type\":\"float\"},{\"name\":\"final_price\",\"type\":\"float\"},{\"name\":\"limit_price\",\"type\":\"float\"},{\"name\":\"users_num\",\"type\":\"int\"},{\"name\":\"final_record\",\"type\":[\"null\",{\"fields\":[{\"name\":\"goods_id\",\"type\":\"int\"},{\"name\":\"customer_mobile\",\"type\":[\"null\",\"string\"]},{\"name\":\"customer_mobile_region\",\"type\":[\"null\",\"string\"]},{\"name\":\"customer_idcard\",\"type\":[\"null\",\"string\"]},{\"name\":\"customer_username\",\"type\":[\"null\",\"string\"]},{\"name\":\"bid_price\",\"type\":\"float\"},{\"name\":\"timestamp\",\"type\":\"long\"}],\"name\":\"MessageAuctionRecord\",\"namespace\":\"proto\",\"type\":\"record\"}]},{\"name\":\"auction_records\",\"type\":{\"items\":\"proto.MessageAuctionRecord\",\"type\":\"array\"}}],\"name\":\"MessageAuctionGoods\",\"namespace\":\"proto\",\"type\":\"record\"}]}],\"name\":\"proto.MessageAuctionInfo\",\"type\":\"record\"}"
}

func (r *MessageAuctionInfo) SchemaName() string {
	return "proto.MessageAuctionInfo"
}

func (_ *MessageAuctionInfo) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *MessageAuctionInfo) SetInt(v int32) { panic("Unsupported operation") }
func (_ *MessageAuctionInfo) SetLong(v int64) { panic("Unsupported operation") }
func (_ *MessageAuctionInfo) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *MessageAuctionInfo) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *MessageAuctionInfo) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *MessageAuctionInfo) SetString(v string) { panic("Unsupported operation") }
func (_ *MessageAuctionInfo) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *MessageAuctionInfo) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
			return (*types.Int)(&r.Remain_seconds)
		
	
	case 1:
		
			r.Goods = NewGoodsUnion()
	
		
		
			return r.Goods
		
	
	}
	panic("Unknown field index")
}

func (r *MessageAuctionInfo) SetDefault(i int) {
	switch (i) {
	
        
	
        
	
	}
	panic("Unknown field index")
}

func (_ *MessageAuctionInfo) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *MessageAuctionInfo) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *MessageAuctionInfo) Finalize() { }
