// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Message_forward_to_customerUnionTypeEnum int
const (

	 Message_forward_to_customerUnionTypeEnumNull Message_forward_to_customerUnionTypeEnum = 0

	 Message_forward_to_customerUnionTypeEnumMessageForward Message_forward_to_customerUnionTypeEnum = 1

)

type Message_forward_to_customerUnion struct {

	Null *types.NullVal

	MessageForward *MessageForward

	UnionType Message_forward_to_customerUnionTypeEnum
}

func writeMessage_forward_to_customerUnion(r *Message_forward_to_customerUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Message_forward_to_customerUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Message_forward_to_customerUnionTypeEnumMessageForward:
		return writeMessageForward(r.MessageForward, w)
        
	}
	return fmt.Errorf("invalid value for *Message_forward_to_customerUnion")
}

func NewMessage_forward_to_customerUnion() *Message_forward_to_customerUnion {
	return &Message_forward_to_customerUnion{}
}

func (_ *Message_forward_to_customerUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Message_forward_to_customerUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Message_forward_to_customerUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Message_forward_to_customerUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Message_forward_to_customerUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Message_forward_to_customerUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Message_forward_to_customerUnion) SetLong(v int64) { 
	r.UnionType = (Message_forward_to_customerUnionTypeEnum)(v)
}
func (r *Message_forward_to_customerUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.MessageForward = NewMessageForward()
		
		
		return r.MessageForward
		
	
	}
	panic("Unknown field index")
}
func (_ *Message_forward_to_customerUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Message_forward_to_customerUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Message_forward_to_customerUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Message_forward_to_customerUnion) Finalize()  { }
