// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type MessageGlobalState struct {

	
	
		GlobalState GlobalState
	

}

func NewMessageGlobalState() (*MessageGlobalState) {
	return &MessageGlobalState{}
}

func DeserializeMessageGlobalState(r io.Reader) (*MessageGlobalState, error) {
	t := NewMessageGlobalState()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeMessageGlobalStateFromSchema(r io.Reader, schema string) (*MessageGlobalState, error) {
	t := NewMessageGlobalState()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeMessageGlobalState(r *MessageGlobalState, w io.Writer) error {
	var err error
	
	err = writeGlobalState( r.GlobalState, w)
	if err != nil {
		return err			
	}
	
	return err
}

func (r *MessageGlobalState) Serialize(w io.Writer) error {
	return writeMessageGlobalState(r, w)
}

func (r *MessageGlobalState) Schema() string {
	return "{\"fields\":[{\"name\":\"globalState\",\"type\":{\"name\":\"enum.GlobalState\",\"symbols\":[\"awating_starting\",\"starting_animations\",\"speeching\",\"aution\",\"products\",\"earnest_money\",\"discount_strategy\",\"chat_with_advisor\",\"activity_ends\"],\"type\":\"enum\"}}],\"name\":\"proto.MessageGlobalState\",\"type\":\"record\"}"
}

func (r *MessageGlobalState) SchemaName() string {
	return "proto.MessageGlobalState"
}

func (_ *MessageGlobalState) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *MessageGlobalState) SetInt(v int32) { panic("Unsupported operation") }
func (_ *MessageGlobalState) SetLong(v int64) { panic("Unsupported operation") }
func (_ *MessageGlobalState) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *MessageGlobalState) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *MessageGlobalState) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *MessageGlobalState) SetString(v string) { panic("Unsupported operation") }
func (_ *MessageGlobalState) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *MessageGlobalState) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
			return (*types.Int)(&r.GlobalState)
		
	
	}
	panic("Unknown field index")
}

func (r *MessageGlobalState) SetDefault(i int) {
	switch (i) {
	
        
	
	}
	panic("Unknown field index")
}

func (_ *MessageGlobalState) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *MessageGlobalState) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *MessageGlobalState) Finalize() { }
