// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Message_game_configUnionTypeEnum int
const (

	 Message_game_configUnionTypeEnumNull Message_game_configUnionTypeEnum = 0

	 Message_game_configUnionTypeEnumMessageGameConfig Message_game_configUnionTypeEnum = 1

)

type Message_game_configUnion struct {

	Null *types.NullVal

	MessageGameConfig *MessageGameConfig

	UnionType Message_game_configUnionTypeEnum
}

func writeMessage_game_configUnion(r *Message_game_configUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Message_game_configUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Message_game_configUnionTypeEnumMessageGameConfig:
		return writeMessageGameConfig(r.MessageGameConfig, w)
        
	}
	return fmt.Errorf("invalid value for *Message_game_configUnion")
}

func NewMessage_game_configUnion() *Message_game_configUnion {
	return &Message_game_configUnion{}
}

func (_ *Message_game_configUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Message_game_configUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Message_game_configUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Message_game_configUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Message_game_configUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Message_game_configUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Message_game_configUnion) SetLong(v int64) { 
	r.UnionType = (Message_game_configUnionTypeEnum)(v)
}
func (r *Message_game_configUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.MessageGameConfig = NewMessageGameConfig()
		
		
		return r.MessageGameConfig
		
	
	}
	panic("Unknown field index")
}
func (_ *Message_game_configUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Message_game_configUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Message_game_configUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Message_game_configUnion) Finalize()  { }
