// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Message_room_waiting_customersUnionTypeEnum int
const (

	 Message_room_waiting_customersUnionTypeEnumNull Message_room_waiting_customersUnionTypeEnum = 0

	 Message_room_waiting_customersUnionTypeEnumMessageRoomWaitingCustomers Message_room_waiting_customersUnionTypeEnum = 1

)

type Message_room_waiting_customersUnion struct {

	Null *types.NullVal

	MessageRoomWaitingCustomers *MessageRoomWaitingCustomers

	UnionType Message_room_waiting_customersUnionTypeEnum
}

func writeMessage_room_waiting_customersUnion(r *Message_room_waiting_customersUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Message_room_waiting_customersUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Message_room_waiting_customersUnionTypeEnumMessageRoomWaitingCustomers:
		return writeMessageRoomWaitingCustomers(r.MessageRoomWaitingCustomers, w)
        
	}
	return fmt.Errorf("invalid value for *Message_room_waiting_customersUnion")
}

func NewMessage_room_waiting_customersUnion() *Message_room_waiting_customersUnion {
	return &Message_room_waiting_customersUnion{}
}

func (_ *Message_room_waiting_customersUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Message_room_waiting_customersUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Message_room_waiting_customersUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Message_room_waiting_customersUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Message_room_waiting_customersUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Message_room_waiting_customersUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Message_room_waiting_customersUnion) SetLong(v int64) { 
	r.UnionType = (Message_room_waiting_customersUnionTypeEnum)(v)
}
func (r *Message_room_waiting_customersUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.MessageRoomWaitingCustomers = NewMessageRoomWaitingCustomers()
		
		
		return r.MessageRoomWaitingCustomers
		
	
	}
	panic("Unknown field index")
}
func (_ *Message_room_waiting_customersUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Message_room_waiting_customersUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Message_room_waiting_customersUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Message_room_waiting_customersUnion) Finalize()  { }
