// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Message_auction_infoUnionTypeEnum int
const (

	 Message_auction_infoUnionTypeEnumNull Message_auction_infoUnionTypeEnum = 0

	 Message_auction_infoUnionTypeEnumMessageAuctionInfo Message_auction_infoUnionTypeEnum = 1

)

type Message_auction_infoUnion struct {

	Null *types.NullVal

	MessageAuctionInfo *MessageAuctionInfo

	UnionType Message_auction_infoUnionTypeEnum
}

func writeMessage_auction_infoUnion(r *Message_auction_infoUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Message_auction_infoUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Message_auction_infoUnionTypeEnumMessageAuctionInfo:
		return writeMessageAuctionInfo(r.MessageAuctionInfo, w)
        
	}
	return fmt.Errorf("invalid value for *Message_auction_infoUnion")
}

func NewMessage_auction_infoUnion() *Message_auction_infoUnion {
	return &Message_auction_infoUnion{}
}

func (_ *Message_auction_infoUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Message_auction_infoUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Message_auction_infoUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Message_auction_infoUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Message_auction_infoUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Message_auction_infoUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Message_auction_infoUnion) SetLong(v int64) { 
	r.UnionType = (Message_auction_infoUnionTypeEnum)(v)
}
func (r *Message_auction_infoUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.MessageAuctionInfo = NewMessageAuctionInfo()
		
		
		return r.MessageAuctionInfo
		
	
	}
	panic("Unknown field index")
}
func (_ *Message_auction_infoUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Message_auction_infoUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Message_auction_infoUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Message_auction_infoUnion) Finalize()  { }
