// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Message_game_dataUnionTypeEnum int
const (

	 Message_game_dataUnionTypeEnumNull Message_game_dataUnionTypeEnum = 0

	 Message_game_dataUnionTypeEnumMessageGameResult Message_game_dataUnionTypeEnum = 1

)

type Message_game_dataUnion struct {

	Null *types.NullVal

	MessageGameResult *MessageGameResult

	UnionType Message_game_dataUnionTypeEnum
}

func writeMessage_game_dataUnion(r *Message_game_dataUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Message_game_dataUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Message_game_dataUnionTypeEnumMessageGameResult:
		return writeMessageGameResult(r.MessageGameResult, w)
        
	}
	return fmt.Errorf("invalid value for *Message_game_dataUnion")
}

func NewMessage_game_dataUnion() *Message_game_dataUnion {
	return &Message_game_dataUnion{}
}

func (_ *Message_game_dataUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Message_game_dataUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Message_game_dataUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Message_game_dataUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Message_game_dataUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Message_game_dataUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Message_game_dataUnion) SetLong(v int64) { 
	r.UnionType = (Message_game_dataUnionTypeEnum)(v)
}
func (r *Message_game_dataUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.MessageGameResult = NewMessageGameResult()
		
		
		return r.MessageGameResult
		
	
	}
	panic("Unknown field index")
}
func (_ *Message_game_dataUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Message_game_dataUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Message_game_dataUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Message_game_dataUnion) Finalize()  { }
