// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Message_room_infoUnionTypeEnum int
const (

	 Message_room_infoUnionTypeEnumNull Message_room_infoUnionTypeEnum = 0

	 Message_room_infoUnionTypeEnumMessageRoomInfo Message_room_infoUnionTypeEnum = 1

)

type Message_room_infoUnion struct {

	Null *types.NullVal

	MessageRoomInfo *MessageRoomInfo

	UnionType Message_room_infoUnionTypeEnum
}

func writeMessage_room_infoUnion(r *Message_room_infoUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Message_room_infoUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Message_room_infoUnionTypeEnumMessageRoomInfo:
		return writeMessageRoomInfo(r.MessageRoomInfo, w)
        
	}
	return fmt.Errorf("invalid value for *Message_room_infoUnion")
}

func NewMessage_room_infoUnion() *Message_room_infoUnion {
	return &Message_room_infoUnion{}
}

func (_ *Message_room_infoUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Message_room_infoUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Message_room_infoUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Message_room_infoUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Message_room_infoUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Message_room_infoUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Message_room_infoUnion) SetLong(v int64) { 
	r.UnionType = (Message_room_infoUnionTypeEnum)(v)
}
func (r *Message_room_infoUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.MessageRoomInfo = NewMessageRoomInfo()
		
		
		return r.MessageRoomInfo
		
	
	}
	panic("Unknown field index")
}
func (_ *Message_room_infoUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Message_room_infoUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Message_room_infoUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Message_room_infoUnion) Finalize()  { }
