// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Message_broadcastUnionTypeEnum int
const (

	 Message_broadcastUnionTypeEnumNull Message_broadcastUnionTypeEnum = 0

	 Message_broadcastUnionTypeEnumMessageForward Message_broadcastUnionTypeEnum = 1

)

type Message_broadcastUnion struct {

	Null *types.NullVal

	MessageForward *MessageForward

	UnionType Message_broadcastUnionTypeEnum
}

func writeMessage_broadcastUnion(r *Message_broadcastUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Message_broadcastUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Message_broadcastUnionTypeEnumMessageForward:
		return writeMessageForward(r.MessageForward, w)
        
	}
	return fmt.Errorf("invalid value for *Message_broadcastUnion")
}

func NewMessage_broadcastUnion() *Message_broadcastUnion {
	return &Message_broadcastUnion{}
}

func (_ *Message_broadcastUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Message_broadcastUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Message_broadcastUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Message_broadcastUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Message_broadcastUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Message_broadcastUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Message_broadcastUnion) SetLong(v int64) { 
	r.UnionType = (Message_broadcastUnionTypeEnum)(v)
}
func (r *Message_broadcastUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.MessageForward = NewMessageForward()
		
		
		return r.MessageForward
		
	
	}
	panic("Unknown field index")
}
func (_ *Message_broadcastUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Message_broadcastUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Message_broadcastUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Message_broadcastUnion) Finalize()  { }
