// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type MobileUnionTypeEnum int
const (

	 MobileUnionTypeEnumNull MobileUnionTypeEnum = 0

	 MobileUnionTypeEnumString MobileUnionTypeEnum = 1

)

type MobileUnion struct {

	Null *types.NullVal

	String string

	UnionType MobileUnionTypeEnum
}

func writeMobileUnion(r *MobileUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case MobileUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case MobileUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *MobileUnion")
}

func NewMobileUnion() *MobileUnion {
	return &MobileUnion{}
}

func (_ *MobileUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *MobileUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *MobileUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *MobileUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *MobileUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *MobileUnion) SetString(v string) { panic("Unsupported operation") }
func (r *MobileUnion) SetLong(v int64) { 
	r.UnionType = (MobileUnionTypeEnum)(v)
}
func (r *MobileUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *MobileUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *MobileUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *MobileUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *MobileUnion) Finalize()  { }
