// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type MobileRegionUnionTypeEnum int
const (

	 MobileRegionUnionTypeEnumNull MobileRegionUnionTypeEnum = 0

	 MobileRegionUnionTypeEnumString MobileRegionUnionTypeEnum = 1

)

type MobileRegionUnion struct {

	Null *types.NullVal

	String string

	UnionType MobileRegionUnionTypeEnum
}

func writeMobileRegionUnion(r *MobileRegionUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case MobileRegionUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case MobileRegionUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *MobileRegionUnion")
}

func NewMobileRegionUnion() *MobileRegionUnion {
	return &MobileRegionUnion{}
}

func (_ *MobileRegionUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *MobileRegionUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *MobileRegionUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *MobileRegionUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *MobileRegionUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *MobileRegionUnion) SetString(v string) { panic("Unsupported operation") }
func (r *MobileRegionUnion) SetLong(v int64) { 
	r.UnionType = (MobileRegionUnionTypeEnum)(v)
}
func (r *MobileRegionUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *MobileRegionUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *MobileRegionUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *MobileRegionUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *MobileRegionUnion) Finalize()  { }
