// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package avro

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type RequestSalesAdvisorSignin struct {

	
	
		Sales_advisor_id *UnionNullString
	

	
	
		Sales_advisor_alias *UnionNullString
	

}

func NewRequestSalesAdvisorSignin() (*RequestSalesAdvisorSignin) {
	return &RequestSalesAdvisorSignin{}
}

func DeserializeRequestSalesAdvisorSignin(r io.Reader) (*RequestSalesAdvisorSignin, error) {
	t := NewRequestSalesAdvisorSignin()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeRequestSalesAdvisorSigninFromSchema(r io.Reader, schema string) (*RequestSalesAdvisorSignin, error) {
	t := NewRequestSalesAdvisorSignin()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeRequestSalesAdvisorSignin(r *RequestSalesAdvisorSignin, w io.Writer) error {
	var err error
	
	err = writeUnionNullString( r.Sales_advisor_id, w)
	if err != nil {
		return err			
	}
	
	err = writeUnionNullString( r.Sales_advisor_alias, w)
	if err != nil {
		return err			
	}
	
	return err
}

func (r *RequestSalesAdvisorSignin) Serialize(w io.Writer) error {
	return writeRequestSalesAdvisorSignin(r, w)
}

func (r *RequestSalesAdvisorSignin) Schema() string {
	return "{\"fields\":[{\"name\":\"sales_advisor_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"sales_advisor_alias\",\"type\":[\"null\",\"string\"]}],\"name\":\"proto.RequestSalesAdvisorSignin\",\"type\":\"record\"}"
}

func (r *RequestSalesAdvisorSignin) SchemaName() string {
	return "proto.RequestSalesAdvisorSignin"
}

func (_ *RequestSalesAdvisorSignin) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorSignin) SetInt(v int32) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorSignin) SetLong(v int64) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorSignin) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorSignin) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorSignin) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorSignin) SetString(v string) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorSignin) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *RequestSalesAdvisorSignin) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
			r.Sales_advisor_id = NewUnionNullString()
	
		
		
			return r.Sales_advisor_id
		
	
	case 1:
		
			r.Sales_advisor_alias = NewUnionNullString()
	
		
		
			return r.Sales_advisor_alias
		
	
	}
	panic("Unknown field index")
}

func (r *RequestSalesAdvisorSignin) SetDefault(i int) {
	switch (i) {
	
        
	
        
	
	}
	panic("Unknown field index")
}

func (_ *RequestSalesAdvisorSignin) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorSignin) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorSignin) Finalize() { }
