// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type RequestCustomerJoinQueue struct {

	
	
		Mobile *MapString
	

}

func NewRequestCustomerJoinQueue() (*RequestCustomerJoinQueue) {
	return &RequestCustomerJoinQueue{}
}

func DeserializeRequestCustomerJoinQueue(r io.Reader) (*RequestCustomerJoinQueue, error) {
	t := NewRequestCustomerJoinQueue()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeRequestCustomerJoinQueueFromSchema(r io.Reader, schema string) (*RequestCustomerJoinQueue, error) {
	t := NewRequestCustomerJoinQueue()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeRequestCustomerJoinQueue(r *RequestCustomerJoinQueue, w io.Writer) error {
	var err error
	
	err = writeMapString( r.Mobile, w)
	if err != nil {
		return err			
	}
	
	return err
}

func (r *RequestCustomerJoinQueue) Serialize(w io.Writer) error {
	return writeRequestCustomerJoinQueue(r, w)
}

func (r *RequestCustomerJoinQueue) Schema() string {
	return "{\"fields\":[{\"name\":\"mobile\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}],\"name\":\"proto.RequestCustomerJoinQueue\",\"type\":\"record\"}"
}

func (r *RequestCustomerJoinQueue) SchemaName() string {
	return "proto.RequestCustomerJoinQueue"
}

func (_ *RequestCustomerJoinQueue) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *RequestCustomerJoinQueue) SetInt(v int32) { panic("Unsupported operation") }
func (_ *RequestCustomerJoinQueue) SetLong(v int64) { panic("Unsupported operation") }
func (_ *RequestCustomerJoinQueue) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *RequestCustomerJoinQueue) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *RequestCustomerJoinQueue) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *RequestCustomerJoinQueue) SetString(v string) { panic("Unsupported operation") }
func (_ *RequestCustomerJoinQueue) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *RequestCustomerJoinQueue) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
			r.Mobile = NewMapString()
	
		
		
			return r.Mobile
		
	
	}
	panic("Unknown field index")
}

func (r *RequestCustomerJoinQueue) SetDefault(i int) {
	switch (i) {
	
        
	
	}
	panic("Unknown field index")
}

func (_ *RequestCustomerJoinQueue) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *RequestCustomerJoinQueue) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *RequestCustomerJoinQueue) Finalize() { }
