// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type RequestSalesAdvisorBuildContract struct {

	
	
		Filename string
	

	
	
		Filebytes []byte
	

}

func NewRequestSalesAdvisorBuildContract() (*RequestSalesAdvisorBuildContract) {
	return &RequestSalesAdvisorBuildContract{}
}

func DeserializeRequestSalesAdvisorBuildContract(r io.Reader) (*RequestSalesAdvisorBuildContract, error) {
	t := NewRequestSalesAdvisorBuildContract()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeRequestSalesAdvisorBuildContractFromSchema(r io.Reader, schema string) (*RequestSalesAdvisorBuildContract, error) {
	t := NewRequestSalesAdvisorBuildContract()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeRequestSalesAdvisorBuildContract(r *RequestSalesAdvisorBuildContract, w io.Writer) error {
	var err error
	
	err = vm.WriteString( r.Filename, w)
	if err != nil {
		return err			
	}
	
	err = vm.WriteBytes( r.Filebytes, w)
	if err != nil {
		return err			
	}
	
	return err
}

func (r *RequestSalesAdvisorBuildContract) Serialize(w io.Writer) error {
	return writeRequestSalesAdvisorBuildContract(r, w)
}

func (r *RequestSalesAdvisorBuildContract) Schema() string {
	return "{\"fields\":[{\"name\":\"filename\",\"type\":\"string\"},{\"name\":\"filebytes\",\"type\":\"bytes\"}],\"name\":\"proto.RequestSalesAdvisorBuildContract\",\"type\":\"record\"}"
}

func (r *RequestSalesAdvisorBuildContract) SchemaName() string {
	return "proto.RequestSalesAdvisorBuildContract"
}

func (_ *RequestSalesAdvisorBuildContract) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorBuildContract) SetInt(v int32) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorBuildContract) SetLong(v int64) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorBuildContract) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorBuildContract) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorBuildContract) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorBuildContract) SetString(v string) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorBuildContract) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *RequestSalesAdvisorBuildContract) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
			return (*types.String)(&r.Filename)
		
	
	case 1:
		
		
			return (*types.Bytes)(&r.Filebytes)
		
	
	}
	panic("Unknown field index")
}

func (r *RequestSalesAdvisorBuildContract) SetDefault(i int) {
	switch (i) {
	
        
	
        
	
	}
	panic("Unknown field index")
}

func (_ *RequestSalesAdvisorBuildContract) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorBuildContract) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorBuildContract) Finalize() { }
