// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type RequestCustomerStartGame struct {

	
	
		GameID string
	

}

func NewRequestCustomerStartGame() (*RequestCustomerStartGame) {
	return &RequestCustomerStartGame{}
}

func DeserializeRequestCustomerStartGame(r io.Reader) (*RequestCustomerStartGame, error) {
	t := NewRequestCustomerStartGame()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeRequestCustomerStartGameFromSchema(r io.Reader, schema string) (*RequestCustomerStartGame, error) {
	t := NewRequestCustomerStartGame()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeRequestCustomerStartGame(r *RequestCustomerStartGame, w io.Writer) error {
	var err error
	
	err = vm.WriteString( r.GameID, w)
	if err != nil {
		return err			
	}
	
	return err
}

func (r *RequestCustomerStartGame) Serialize(w io.Writer) error {
	return writeRequestCustomerStartGame(r, w)
}

func (r *RequestCustomerStartGame) Schema() string {
	return "{\"fields\":[{\"name\":\"gameID\",\"type\":\"string\"}],\"name\":\"proto.RequestCustomerStartGame\",\"type\":\"record\"}"
}

func (r *RequestCustomerStartGame) SchemaName() string {
	return "proto.RequestCustomerStartGame"
}

func (_ *RequestCustomerStartGame) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *RequestCustomerStartGame) SetInt(v int32) { panic("Unsupported operation") }
func (_ *RequestCustomerStartGame) SetLong(v int64) { panic("Unsupported operation") }
func (_ *RequestCustomerStartGame) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *RequestCustomerStartGame) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *RequestCustomerStartGame) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *RequestCustomerStartGame) SetString(v string) { panic("Unsupported operation") }
func (_ *RequestCustomerStartGame) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *RequestCustomerStartGame) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
			return (*types.String)(&r.GameID)
		
	
	}
	panic("Unknown field index")
}

func (r *RequestCustomerStartGame) SetDefault(i int) {
	switch (i) {
	
        
	
	}
	panic("Unknown field index")
}

func (_ *RequestCustomerStartGame) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *RequestCustomerStartGame) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *RequestCustomerStartGame) Finalize() { }
