// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type RequestSalesAdvisorConfirmPaid struct {

}

func NewRequestSalesAdvisorConfirmPaid() (*RequestSalesAdvisorConfirmPaid) {
	return &RequestSalesAdvisorConfirmPaid{}
}

func DeserializeRequestSalesAdvisorConfirmPaid(r io.Reader) (*RequestSalesAdvisorConfirmPaid, error) {
	t := NewRequestSalesAdvisorConfirmPaid()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeRequestSalesAdvisorConfirmPaidFromSchema(r io.Reader, schema string) (*RequestSalesAdvisorConfirmPaid, error) {
	t := NewRequestSalesAdvisorConfirmPaid()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeRequestSalesAdvisorConfirmPaid(r *RequestSalesAdvisorConfirmPaid, w io.Writer) error {
	var err error
	
	return err
}

func (r *RequestSalesAdvisorConfirmPaid) Serialize(w io.Writer) error {
	return writeRequestSalesAdvisorConfirmPaid(r, w)
}

func (r *RequestSalesAdvisorConfirmPaid) Schema() string {
	return "{\"fields\":[],\"name\":\"proto.RequestSalesAdvisorConfirmPaid\",\"type\":\"record\"}"
}

func (r *RequestSalesAdvisorConfirmPaid) SchemaName() string {
	return "proto.RequestSalesAdvisorConfirmPaid"
}

func (_ *RequestSalesAdvisorConfirmPaid) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorConfirmPaid) SetInt(v int32) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorConfirmPaid) SetLong(v int64) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorConfirmPaid) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorConfirmPaid) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorConfirmPaid) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorConfirmPaid) SetString(v string) { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorConfirmPaid) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *RequestSalesAdvisorConfirmPaid) Get(i int) types.Field {
	switch (i) {
	
	}
	panic("Unknown field index")
}

func (r *RequestSalesAdvisorConfirmPaid) SetDefault(i int) {
	switch (i) {
	
	}
	panic("Unknown field index")
}

func (_ *RequestSalesAdvisorConfirmPaid) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorConfirmPaid) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *RequestSalesAdvisorConfirmPaid) Finalize() { }
