// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Request_customer_build_signatureUnionTypeEnum int
const (

	 Request_customer_build_signatureUnionTypeEnumNull Request_customer_build_signatureUnionTypeEnum = 0

	 Request_customer_build_signatureUnionTypeEnumRequestCustomerBuildSignature Request_customer_build_signatureUnionTypeEnum = 1

)

type Request_customer_build_signatureUnion struct {

	Null *types.NullVal

	RequestCustomerBuildSignature *RequestCustomerBuildSignature

	UnionType Request_customer_build_signatureUnionTypeEnum
}

func writeRequest_customer_build_signatureUnion(r *Request_customer_build_signatureUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Request_customer_build_signatureUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Request_customer_build_signatureUnionTypeEnumRequestCustomerBuildSignature:
		return writeRequestCustomerBuildSignature(r.RequestCustomerBuildSignature, w)
        
	}
	return fmt.Errorf("invalid value for *Request_customer_build_signatureUnion")
}

func NewRequest_customer_build_signatureUnion() *Request_customer_build_signatureUnion {
	return &Request_customer_build_signatureUnion{}
}

func (_ *Request_customer_build_signatureUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Request_customer_build_signatureUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Request_customer_build_signatureUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Request_customer_build_signatureUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Request_customer_build_signatureUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Request_customer_build_signatureUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Request_customer_build_signatureUnion) SetLong(v int64) { 
	r.UnionType = (Request_customer_build_signatureUnionTypeEnum)(v)
}
func (r *Request_customer_build_signatureUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestCustomerBuildSignature = NewRequestCustomerBuildSignature()
		
		
		return r.RequestCustomerBuildSignature
		
	
	}
	panic("Unknown field index")
}
func (_ *Request_customer_build_signatureUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Request_customer_build_signatureUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Request_customer_build_signatureUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Request_customer_build_signatureUnion) Finalize()  { }
