// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type RequestCustomerAuctionBid struct {

	
	
		Bid_price float32
	

}

func NewRequestCustomerAuctionBid() (*RequestCustomerAuctionBid) {
	return &RequestCustomerAuctionBid{}
}

func DeserializeRequestCustomerAuctionBid(r io.Reader) (*RequestCustomerAuctionBid, error) {
	t := NewRequestCustomerAuctionBid()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeRequestCustomerAuctionBidFromSchema(r io.Reader, schema string) (*RequestCustomerAuctionBid, error) {
	t := NewRequestCustomerAuctionBid()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeRequestCustomerAuctionBid(r *RequestCustomerAuctionBid, w io.Writer) error {
	var err error
	
	err = vm.WriteFloat( r.Bid_price, w)
	if err != nil {
		return err			
	}
	
	return err
}

func (r *RequestCustomerAuctionBid) Serialize(w io.Writer) error {
	return writeRequestCustomerAuctionBid(r, w)
}

func (r *RequestCustomerAuctionBid) Schema() string {
	return "{\"fields\":[{\"name\":\"bid_price\",\"type\":\"float\"}],\"name\":\"proto.RequestCustomerAuctionBid\",\"type\":\"record\"}"
}

func (r *RequestCustomerAuctionBid) SchemaName() string {
	return "proto.RequestCustomerAuctionBid"
}

func (_ *RequestCustomerAuctionBid) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *RequestCustomerAuctionBid) SetInt(v int32) { panic("Unsupported operation") }
func (_ *RequestCustomerAuctionBid) SetLong(v int64) { panic("Unsupported operation") }
func (_ *RequestCustomerAuctionBid) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *RequestCustomerAuctionBid) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *RequestCustomerAuctionBid) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *RequestCustomerAuctionBid) SetString(v string) { panic("Unsupported operation") }
func (_ *RequestCustomerAuctionBid) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *RequestCustomerAuctionBid) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
			return (*types.Float)(&r.Bid_price)
		
	
	}
	panic("Unknown field index")
}

func (r *RequestCustomerAuctionBid) SetDefault(i int) {
	switch (i) {
	
        
	
	}
	panic("Unknown field index")
}

func (_ *RequestCustomerAuctionBid) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *RequestCustomerAuctionBid) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *RequestCustomerAuctionBid) Finalize() { }
