// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type RequestCustomerUploadGameScore struct {

	
	
		GameID string
	

	
	
		Score int32
	

}

func NewRequestCustomerUploadGameScore() (*RequestCustomerUploadGameScore) {
	return &RequestCustomerUploadGameScore{}
}

func DeserializeRequestCustomerUploadGameScore(r io.Reader) (*RequestCustomerUploadGameScore, error) {
	t := NewRequestCustomerUploadGameScore()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeRequestCustomerUploadGameScoreFromSchema(r io.Reader, schema string) (*RequestCustomerUploadGameScore, error) {
	t := NewRequestCustomerUploadGameScore()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeRequestCustomerUploadGameScore(r *RequestCustomerUploadGameScore, w io.Writer) error {
	var err error
	
	err = vm.WriteString( r.GameID, w)
	if err != nil {
		return err			
	}
	
	err = vm.WriteInt( r.Score, w)
	if err != nil {
		return err			
	}
	
	return err
}

func (r *RequestCustomerUploadGameScore) Serialize(w io.Writer) error {
	return writeRequestCustomerUploadGameScore(r, w)
}

func (r *RequestCustomerUploadGameScore) Schema() string {
	return "{\"fields\":[{\"name\":\"gameID\",\"type\":\"string\"},{\"name\":\"score\",\"type\":\"int\"}],\"name\":\"proto.RequestCustomerUploadGameScore\",\"type\":\"record\"}"
}

func (r *RequestCustomerUploadGameScore) SchemaName() string {
	return "proto.RequestCustomerUploadGameScore"
}

func (_ *RequestCustomerUploadGameScore) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *RequestCustomerUploadGameScore) SetInt(v int32) { panic("Unsupported operation") }
func (_ *RequestCustomerUploadGameScore) SetLong(v int64) { panic("Unsupported operation") }
func (_ *RequestCustomerUploadGameScore) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *RequestCustomerUploadGameScore) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *RequestCustomerUploadGameScore) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *RequestCustomerUploadGameScore) SetString(v string) { panic("Unsupported operation") }
func (_ *RequestCustomerUploadGameScore) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *RequestCustomerUploadGameScore) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
			return (*types.String)(&r.GameID)
		
	
	case 1:
		
		
			return (*types.Int)(&r.Score)
		
	
	}
	panic("Unknown field index")
}

func (r *RequestCustomerUploadGameScore) SetDefault(i int) {
	switch (i) {
	
        
	
        
	
	}
	panic("Unknown field index")
}

func (_ *RequestCustomerUploadGameScore) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *RequestCustomerUploadGameScore) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *RequestCustomerUploadGameScore) Finalize() { }
