// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Sales_advisor_signinUnionTypeEnum int
const (

	 Sales_advisor_signinUnionTypeEnumNull Sales_advisor_signinUnionTypeEnum = 0

	 Sales_advisor_signinUnionTypeEnumRequestSalesAdvisorSignin Sales_advisor_signinUnionTypeEnum = 1

)

type Sales_advisor_signinUnion struct {

	Null *types.NullVal

	RequestSalesAdvisorSignin *RequestSalesAdvisorSignin

	UnionType Sales_advisor_signinUnionTypeEnum
}

func writeSales_advisor_signinUnion(r *Sales_advisor_signinUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Sales_advisor_signinUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Sales_advisor_signinUnionTypeEnumRequestSalesAdvisorSignin:
		return writeRequestSalesAdvisorSignin(r.RequestSalesAdvisorSignin, w)
        
	}
	return fmt.Errorf("invalid value for *Sales_advisor_signinUnion")
}

func NewSales_advisor_signinUnion() *Sales_advisor_signinUnion {
	return &Sales_advisor_signinUnion{}
}

func (_ *Sales_advisor_signinUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Sales_advisor_signinUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Sales_advisor_signinUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Sales_advisor_signinUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Sales_advisor_signinUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Sales_advisor_signinUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Sales_advisor_signinUnion) SetLong(v int64) { 
	r.UnionType = (Sales_advisor_signinUnionTypeEnum)(v)
}
func (r *Sales_advisor_signinUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestSalesAdvisorSignin = NewRequestSalesAdvisorSignin()
		
		
		return r.RequestSalesAdvisorSignin
		
	
	}
	panic("Unknown field index")
}
func (_ *Sales_advisor_signinUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Sales_advisor_signinUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Sales_advisor_signinUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Sales_advisor_signinUnion) Finalize()  { }
