// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Sales_advisor_confirm_paidUnionTypeEnum int
const (

	 Sales_advisor_confirm_paidUnionTypeEnumNull Sales_advisor_confirm_paidUnionTypeEnum = 0

	 Sales_advisor_confirm_paidUnionTypeEnumRequestSalesAdvisorConfirmPaid Sales_advisor_confirm_paidUnionTypeEnum = 1

)

type Sales_advisor_confirm_paidUnion struct {

	Null *types.NullVal

	RequestSalesAdvisorConfirmPaid *RequestSalesAdvisorConfirmPaid

	UnionType Sales_advisor_confirm_paidUnionTypeEnum
}

func writeSales_advisor_confirm_paidUnion(r *Sales_advisor_confirm_paidUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Sales_advisor_confirm_paidUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Sales_advisor_confirm_paidUnionTypeEnumRequestSalesAdvisorConfirmPaid:
		return writeRequestSalesAdvisorConfirmPaid(r.RequestSalesAdvisorConfirmPaid, w)
        
	}
	return fmt.Errorf("invalid value for *Sales_advisor_confirm_paidUnion")
}

func NewSales_advisor_confirm_paidUnion() *Sales_advisor_confirm_paidUnion {
	return &Sales_advisor_confirm_paidUnion{}
}

func (_ *Sales_advisor_confirm_paidUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Sales_advisor_confirm_paidUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Sales_advisor_confirm_paidUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Sales_advisor_confirm_paidUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Sales_advisor_confirm_paidUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Sales_advisor_confirm_paidUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Sales_advisor_confirm_paidUnion) SetLong(v int64) { 
	r.UnionType = (Sales_advisor_confirm_paidUnionTypeEnum)(v)
}
func (r *Sales_advisor_confirm_paidUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestSalesAdvisorConfirmPaid = NewRequestSalesAdvisorConfirmPaid()
		
		
		return r.RequestSalesAdvisorConfirmPaid
		
	
	}
	panic("Unknown field index")
}
func (_ *Sales_advisor_confirm_paidUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Sales_advisor_confirm_paidUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Sales_advisor_confirm_paidUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Sales_advisor_confirm_paidUnion) Finalize()  { }
