// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Sales_advisor_idUnionTypeEnum int
const (

	 Sales_advisor_idUnionTypeEnumNull Sales_advisor_idUnionTypeEnum = 0

	 Sales_advisor_idUnionTypeEnumString Sales_advisor_idUnionTypeEnum = 1

)

type Sales_advisor_idUnion struct {

	Null *types.NullVal

	String string

	UnionType Sales_advisor_idUnionTypeEnum
}

func writeSales_advisor_idUnion(r *Sales_advisor_idUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Sales_advisor_idUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Sales_advisor_idUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *Sales_advisor_idUnion")
}

func NewSales_advisor_idUnion() *Sales_advisor_idUnion {
	return &Sales_advisor_idUnion{}
}

func (_ *Sales_advisor_idUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Sales_advisor_idUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Sales_advisor_idUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Sales_advisor_idUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Sales_advisor_idUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Sales_advisor_idUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Sales_advisor_idUnion) SetLong(v int64) { 
	r.UnionType = (Sales_advisor_idUnionTypeEnum)(v)
}
func (r *Sales_advisor_idUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *Sales_advisor_idUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Sales_advisor_idUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Sales_advisor_idUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Sales_advisor_idUnion) Finalize()  { }
