// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Sales_advisor_build_contractUnionTypeEnum int
const (

	 Sales_advisor_build_contractUnionTypeEnumNull Sales_advisor_build_contractUnionTypeEnum = 0

	 Sales_advisor_build_contractUnionTypeEnumRequestSalesAdvisorBuildContract Sales_advisor_build_contractUnionTypeEnum = 1

)

type Sales_advisor_build_contractUnion struct {

	Null *types.NullVal

	RequestSalesAdvisorBuildContract *RequestSalesAdvisorBuildContract

	UnionType Sales_advisor_build_contractUnionTypeEnum
}

func writeSales_advisor_build_contractUnion(r *Sales_advisor_build_contractUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Sales_advisor_build_contractUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Sales_advisor_build_contractUnionTypeEnumRequestSalesAdvisorBuildContract:
		return writeRequestSalesAdvisorBuildContract(r.RequestSalesAdvisorBuildContract, w)
        
	}
	return fmt.Errorf("invalid value for *Sales_advisor_build_contractUnion")
}

func NewSales_advisor_build_contractUnion() *Sales_advisor_build_contractUnion {
	return &Sales_advisor_build_contractUnion{}
}

func (_ *Sales_advisor_build_contractUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Sales_advisor_build_contractUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Sales_advisor_build_contractUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Sales_advisor_build_contractUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Sales_advisor_build_contractUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Sales_advisor_build_contractUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Sales_advisor_build_contractUnion) SetLong(v int64) { 
	r.UnionType = (Sales_advisor_build_contractUnionTypeEnum)(v)
}
func (r *Sales_advisor_build_contractUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestSalesAdvisorBuildContract = NewRequestSalesAdvisorBuildContract()
		
		
		return r.RequestSalesAdvisorBuildContract
		
	
	}
	panic("Unknown field index")
}
func (_ *Sales_advisor_build_contractUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Sales_advisor_build_contractUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Sales_advisor_build_contractUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Sales_advisor_build_contractUnion) Finalize()  { }
