// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type Sales_advisor_aliasUnionTypeEnum int
const (

	 Sales_advisor_aliasUnionTypeEnumNull Sales_advisor_aliasUnionTypeEnum = 0

	 Sales_advisor_aliasUnionTypeEnumString Sales_advisor_aliasUnionTypeEnum = 1

)

type Sales_advisor_aliasUnion struct {

	Null *types.NullVal

	String string

	UnionType Sales_advisor_aliasUnionTypeEnum
}

func writeSales_advisor_aliasUnion(r *Sales_advisor_aliasUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case Sales_advisor_aliasUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case Sales_advisor_aliasUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *Sales_advisor_aliasUnion")
}

func NewSales_advisor_aliasUnion() *Sales_advisor_aliasUnion {
	return &Sales_advisor_aliasUnion{}
}

func (_ *Sales_advisor_aliasUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *Sales_advisor_aliasUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *Sales_advisor_aliasUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *Sales_advisor_aliasUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *Sales_advisor_aliasUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *Sales_advisor_aliasUnion) SetString(v string) { panic("Unsupported operation") }
func (r *Sales_advisor_aliasUnion) SetLong(v int64) { 
	r.UnionType = (Sales_advisor_aliasUnionTypeEnum)(v)
}
func (r *Sales_advisor_aliasUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *Sales_advisor_aliasUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *Sales_advisor_aliasUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *Sales_advisor_aliasUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *Sales_advisor_aliasUnion) Finalize()  { }
