// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type SecUnionTypeEnum int
const (

	 SecUnionTypeEnumNull SecUnionTypeEnum = 0

	 SecUnionTypeEnumString SecUnionTypeEnum = 1

)

type SecUnion struct {

	Null *types.NullVal

	String string

	UnionType SecUnionTypeEnum
}

func writeSecUnion(r *SecUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case SecUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case SecUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *SecUnion")
}

func NewSecUnion() *SecUnion {
	return &SecUnion{}
}

func (_ *SecUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *SecUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *SecUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *SecUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *SecUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *SecUnion) SetString(v string) { panic("Unsupported operation") }
func (r *SecUnion) SetLong(v int64) { 
	r.UnionType = (SecUnionTypeEnum)(v)
}
func (r *SecUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *SecUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *SecUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *SecUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *SecUnion) Finalize()  { }
