// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type SessionIdUnionTypeEnum int
const (

	 SessionIdUnionTypeEnumNull SessionIdUnionTypeEnum = 0

	 SessionIdUnionTypeEnumString SessionIdUnionTypeEnum = 1

)

type SessionIdUnion struct {

	Null *types.NullVal

	String string

	UnionType SessionIdUnionTypeEnum
}

func writeSessionIdUnion(r *SessionIdUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case SessionIdUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case SessionIdUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *SessionIdUnion")
}

func NewSessionIdUnion() *SessionIdUnion {
	return &SessionIdUnion{}
}

func (_ *SessionIdUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *SessionIdUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *SessionIdUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *SessionIdUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *SessionIdUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *SessionIdUnion) SetString(v string) { panic("Unsupported operation") }
func (r *SessionIdUnion) SetLong(v int64) { 
	r.UnionType = (SessionIdUnionTypeEnum)(v)
}
func (r *SessionIdUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *SessionIdUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *SessionIdUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *SessionIdUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *SessionIdUnion) Finalize()  { }
