// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package protocol

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type SidUnionTypeEnum int
const (

	 SidUnionTypeEnumNull SidUnionTypeEnum = 0

	 SidUnionTypeEnumString SidUnionTypeEnum = 1

)

type SidUnion struct {

	Null *types.NullVal

	String string

	UnionType SidUnionTypeEnum
}

func writeSidUnion(r *SidUnion, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case SidUnionTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case SidUnionTypeEnumString:
		return vm.WriteString(r.String, w)
        
	}
	return fmt.Errorf("invalid value for *SidUnion")
}

func NewSidUnion() *SidUnion {
	return &SidUnion{}
}

func (_ *SidUnion) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *SidUnion) SetInt(v int32) { panic("Unsupported operation") }
func (_ *SidUnion) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *SidUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *SidUnion) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *SidUnion) SetString(v string) { panic("Unsupported operation") }
func (r *SidUnion) SetLong(v int64) { 
	r.UnionType = (SidUnionTypeEnum)(v)
}
func (r *SidUnion) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		
		return (*types.String)(&r.String)
		
	
	}
	panic("Unknown field index")
}
func (_ *SidUnion) SetDefault(i int) { panic("Unsupported operation") }
func (_ *SidUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *SidUnion) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *SidUnion) Finalize()  { }
