// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package avro

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullRequestSalesAdvisorSigninTypeEnum int
const (

	 UnionNullRequestSalesAdvisorSigninTypeEnumNull UnionNullRequestSalesAdvisorSigninTypeEnum = 0

	 UnionNullRequestSalesAdvisorSigninTypeEnumRequestSalesAdvisorSignin UnionNullRequestSalesAdvisorSigninTypeEnum = 1

)

type UnionNullRequestSalesAdvisorSignin struct {

	Null *types.NullVal

	RequestSalesAdvisorSignin *RequestSalesAdvisorSignin

	UnionType UnionNullRequestSalesAdvisorSigninTypeEnum
}

func writeUnionNullRequestSalesAdvisorSignin(r *UnionNullRequestSalesAdvisorSignin, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullRequestSalesAdvisorSigninTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullRequestSalesAdvisorSigninTypeEnumRequestSalesAdvisorSignin:
		return writeRequestSalesAdvisorSignin(r.RequestSalesAdvisorSignin, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullRequestSalesAdvisorSignin")
}

func NewUnionNullRequestSalesAdvisorSignin() *UnionNullRequestSalesAdvisorSignin {
	return &UnionNullRequestSalesAdvisorSignin{}
}

func (_ *UnionNullRequestSalesAdvisorSignin) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorSignin) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorSignin) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorSignin) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorSignin) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorSignin) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullRequestSalesAdvisorSignin) SetLong(v int64) { 
	r.UnionType = (UnionNullRequestSalesAdvisorSigninTypeEnum)(v)
}
func (r *UnionNullRequestSalesAdvisorSignin) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestSalesAdvisorSignin = NewRequestSalesAdvisorSignin()
		
		
		return r.RequestSalesAdvisorSignin
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullRequestSalesAdvisorSignin) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorSignin) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorSignin) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorSignin) Finalize()  { }
