// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package avro

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullRequestSalesAdvisorConfirmPaidTypeEnum int
const (

	 UnionNullRequestSalesAdvisorConfirmPaidTypeEnumNull UnionNullRequestSalesAdvisorConfirmPaidTypeEnum = 0

	 UnionNullRequestSalesAdvisorConfirmPaidTypeEnumRequestSalesAdvisorConfirmPaid UnionNullRequestSalesAdvisorConfirmPaidTypeEnum = 1

)

type UnionNullRequestSalesAdvisorConfirmPaid struct {

	Null *types.NullVal

	RequestSalesAdvisorConfirmPaid *RequestSalesAdvisorConfirmPaid

	UnionType UnionNullRequestSalesAdvisorConfirmPaidTypeEnum
}

func writeUnionNullRequestSalesAdvisorConfirmPaid(r *UnionNullRequestSalesAdvisorConfirmPaid, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullRequestSalesAdvisorConfirmPaidTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullRequestSalesAdvisorConfirmPaidTypeEnumRequestSalesAdvisorConfirmPaid:
		return writeRequestSalesAdvisorConfirmPaid(r.RequestSalesAdvisorConfirmPaid, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullRequestSalesAdvisorConfirmPaid")
}

func NewUnionNullRequestSalesAdvisorConfirmPaid() *UnionNullRequestSalesAdvisorConfirmPaid {
	return &UnionNullRequestSalesAdvisorConfirmPaid{}
}

func (_ *UnionNullRequestSalesAdvisorConfirmPaid) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorConfirmPaid) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorConfirmPaid) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorConfirmPaid) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorConfirmPaid) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorConfirmPaid) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullRequestSalesAdvisorConfirmPaid) SetLong(v int64) { 
	r.UnionType = (UnionNullRequestSalesAdvisorConfirmPaidTypeEnum)(v)
}
func (r *UnionNullRequestSalesAdvisorConfirmPaid) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestSalesAdvisorConfirmPaid = NewRequestSalesAdvisorConfirmPaid()
		
		
		return r.RequestSalesAdvisorConfirmPaid
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullRequestSalesAdvisorConfirmPaid) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorConfirmPaid) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorConfirmPaid) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorConfirmPaid) Finalize()  { }
