// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     lueey.avsc
 */
package avro

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullRequestSalesAdvisorLeaveCustomersTypeEnum int
const (

	 UnionNullRequestSalesAdvisorLeaveCustomersTypeEnumNull UnionNullRequestSalesAdvisorLeaveCustomersTypeEnum = 0

	 UnionNullRequestSalesAdvisorLeaveCustomersTypeEnumRequestSalesAdvisorLeaveCustomers UnionNullRequestSalesAdvisorLeaveCustomersTypeEnum = 1

)

type UnionNullRequestSalesAdvisorLeaveCustomers struct {

	Null *types.NullVal

	RequestSalesAdvisorLeaveCustomers *RequestSalesAdvisorLeaveCustomers

	UnionType UnionNullRequestSalesAdvisorLeaveCustomersTypeEnum
}

func writeUnionNullRequestSalesAdvisorLeaveCustomers(r *UnionNullRequestSalesAdvisorLeaveCustomers, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullRequestSalesAdvisorLeaveCustomersTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullRequestSalesAdvisorLeaveCustomersTypeEnumRequestSalesAdvisorLeaveCustomers:
		return writeRequestSalesAdvisorLeaveCustomers(r.RequestSalesAdvisorLeaveCustomers, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullRequestSalesAdvisorLeaveCustomers")
}

func NewUnionNullRequestSalesAdvisorLeaveCustomers() *UnionNullRequestSalesAdvisorLeaveCustomers {
	return &UnionNullRequestSalesAdvisorLeaveCustomers{}
}

func (_ *UnionNullRequestSalesAdvisorLeaveCustomers) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorLeaveCustomers) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorLeaveCustomers) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorLeaveCustomers) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorLeaveCustomers) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorLeaveCustomers) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullRequestSalesAdvisorLeaveCustomers) SetLong(v int64) { 
	r.UnionType = (UnionNullRequestSalesAdvisorLeaveCustomersTypeEnum)(v)
}
func (r *UnionNullRequestSalesAdvisorLeaveCustomers) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.RequestSalesAdvisorLeaveCustomers = NewRequestSalesAdvisorLeaveCustomers()
		
		
		return r.RequestSalesAdvisorLeaveCustomers
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullRequestSalesAdvisorLeaveCustomers) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorLeaveCustomers) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorLeaveCustomers) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullRequestSalesAdvisorLeaveCustomers) Finalize()  { }
